//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public SANPHAM()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
        }
    
        public string MA { get; set; }
        public string TEN { get; set; }
        public Nullable<double> DONGIABAN { get; set; }
        public string HINHANH { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> LOAISANPHAM { get; set; }
        public Nullable<bool> SANPHAMMOI { get; set; }
        public Nullable<int> NHASANXUAT { get; set; }
        public Nullable<bool> SANPHAMBANCHAY { get; set; }
        public Nullable<bool> DAXOA { get; set; }
        public Nullable<int> MAKHUYENMAI { get; set; }
    
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM1 { get; set; }
        public virtual NHASANXUAT NHASANXUAT1 { get; set; }
    }
}
