//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHTOANONLINE
    {
        public int MA { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> MATHANHVIEN { get; set; }
        public Nullable<bool> DAXOA { get; set; }
    
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
