//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        public THANHVIEN()
        {
            this.THANHTOANONLINEs = new HashSet<THANHTOANONLINE>();
        }
    
        public int MA { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string TEN { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string THONGTINMOTA { get; set; }
        public string ACCESSTOKEN { get; set; }
        public Nullable<int> LOAITHANHVIEN { get; set; }
        public Nullable<bool> DAXOA { get; set; }
    
        public virtual LOAITHANHVIEN LOAITHANHVIEN1 { get; set; }
        public virtual ICollection<THANHTOANONLINE> THANHTOANONLINEs { get; set; }
    }
}
